---
spring:
  profiles:
    active: development
  datasource:
    driver-class-name:  oracle.jdbc.OracleDriver
    druid:
      filters: wall,stat,slf4j
      poolPreparedStatements: true
      stat-view-servlet:
        login-username: scm
        login-password: SCM@druid
  cache:
    caffeine:
      spec: maximumSize=3000,expireAfterAccess=1d
    cache-names: param
  http:
    multipart:
      max-file-size: 20mb
      max-request-size: 20mb
server:
  error:
      whitelabel:
        enabled: false
  port: 9080
  session:
    timeout: 1800
mybatis:
  mapper-locations: classpath:/mybatis/**/*Mapper.xml
pagehelper:
  support-methods-arguments: true
  params: pageNum=page

--- # 开发配置定义

spring:
  profiles: development
  datasource:
    url:  jdbc:oracle:thin:@10.24.10.224:1521:bdcor5
    username: scm
    password: develop
server:
  port: 9080
third-service:
  fastdfs:
    tracker-servers: 10.24.10.225:22122
--- # 生产配置定义

spring:
  profiles: production
  datasource:
    url: jdbc:oracle:thin:@10.24.10.34:1521:jtbiobank
    username: scm
    password: ncrc@2017
server:
  port: 9080
third-service:
  fastdfs:
    tracker-servers: 10.24.10.12:22122